services:
  holder-agent:
    container_name: holder-agent
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
    networks:
      - my_shared_network
    restart: unless-stopped

  holder-frontend:
    container_name: holder-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - holder-agent
    networks:
      - my_shared_network
    restart: unless-stopped
  
networks:
  my_shared_network:
    external: true